# Generated by Django 2.0.7 on 2018-07-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latlng',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
