# Generated by Django 2.0.7 on 2018-07-11 10:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='meta',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
